import { useState } from "react";
import { useMutation } from "convex/react";
import { api } from "../../convex/_generated/api";
import { type CostBreakdown, type Lifestyle, type HousingType, type TravelerType, type WorkStyle, costData } from "../data/costs";

interface LeadModalProps {
  country: string;
  city: string;
  lifestyle: Lifestyle;
  stayLength: number;
  housingType: HousingType;
  travelerType: TravelerType;
  workStyle: WorkStyle;
  breakdown: CostBreakdown;
  onClose: () => void;
}

function getDeviceId(): string {
  let deviceId = localStorage.getItem("tth_device_id");
  if (!deviceId) {
    deviceId = "dev_" + Math.random().toString(36).substring(2) + Date.now().toString(36);
    localStorage.setItem("tth_device_id", deviceId);
  }
  return deviceId;
}

export function LeadModal({
  country,
  city,
  lifestyle,
  stayLength,
  housingType,
  travelerType,
  workStyle,
  breakdown,
  onClose,
}: LeadModalProps) {
  const [email, setEmail] = useState("");
  const [consent, setConsent] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState("");

  const submitLead = useMutation(api.leads.submitLead);
  const countryName = costData[country.toLowerCase()]?.name || country;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || !consent) return;

    setSubmitting(true);
    setError("");

    try {
      await submitLead({
        email,
        consent,
        country,
        city: city || undefined,
        lifestyle,
        stayLength,
        housingType,
        travelerType,
        workStyle,
        total: breakdown.total,
        breakdownJson: JSON.stringify(breakdown),
        deviceId: getDeviceId(),
      });
      setSubmitted(true);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to submit. Please try again.");
    } finally {
      setSubmitting(false);
    }
  };

  const handleDownload = () => {
    // Generate a simple text-based plan
    const planContent = `
TRAVELTOOLHUB - RELOCATION COST PLAN
=====================================

Destination: ${countryName}${city ? ` - ${city}` : ""}
Lifestyle: ${lifestyle.charAt(0).toUpperCase() + lifestyle.slice(1)}
Stay Length: ${stayLength} months
Housing: ${housingType.toUpperCase()}
Traveler Type: ${travelerType === "solo" ? "Solo" : "Couple"}
Work Style: ${workStyle.charAt(0).toUpperCase() + workStyle.slice(1)}

MONTHLY COST BREAKDOWN
----------------------
Rent:            $${breakdown.rent}
Food & Groceries: $${breakdown.food}
Transport:       $${breakdown.transport}
Utilities:       $${breakdown.utilities}
Internet & SIM:  $${breakdown.internet}
Health/Insurance: $${breakdown.health}
Fun & Misc:      $${breakdown.fun}
----------------------
TOTAL:           $${breakdown.total}/month

TOTAL FOR ${stayLength} MONTHS: $${breakdown.total * stayLength}

---
Generated by TravelToolHub
https://traveltoolhub.com
    `.trim();

    const blob = new Blob([planContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `relocation-plan-${country}-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end md:items-center justify-center p-0 md:p-4">
      <div className="absolute inset-0 bg-black/80 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full md:max-w-md bg-slate-900 border border-white/10 rounded-t-3xl md:rounded-2xl shadow-2xl overflow-hidden max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="sticky top-0 bg-slate-900/95 backdrop-blur-xl border-b border-white/10 px-6 py-4 flex items-center justify-between">
          <h3 className="text-lg font-bold text-white">
            {submitted ? "Success!" : "Get Your Relocation Plan"}
          </h3>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-white/10 flex items-center justify-center text-white/60 hover:text-white hover:bg-white/20 transition-colors"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <div className="p-6">
          {submitted ? (
            <div className="text-center space-y-4">
              <div className="w-16 h-16 mx-auto rounded-full bg-teal-500/20 flex items-center justify-center">
                <svg className="w-8 h-8 text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <div>
                <p className="text-white font-medium">Your plan is ready!</p>
                <p className="text-white/50 text-sm mt-1">
                  We&apos;ve sent details to {email}
                </p>
              </div>
              <button
                onClick={handleDownload}
                className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-600 text-white font-bold rounded-xl shadow-lg shadow-teal-500/30 hover:shadow-teal-500/50 transition-all flex items-center justify-center gap-2"
              >
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                </svg>
                Download Plan
              </button>
              <a
                href="https://traveltoolhub.com"
                target="_blank"
                rel="noopener noreferrer"
                className="block w-full py-3 bg-white/5 border border-white/10 text-white/80 font-medium rounded-xl hover:bg-white/10 transition-colors text-center"
              >
                Open TravelToolHub
              </a>
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-4">
              <p className="text-white/60 text-sm">
                Enter your email to receive your personalized relocation cost breakdown for {countryName}.
              </p>

              <div className="space-y-2">
                <label className="block text-xs uppercase tracking-wider text-teal-400/80 font-medium">
                  Email Address *
                </label>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="you@example.com"
                  required
                  className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3.5 text-white placeholder-white/30 focus:outline-none focus:border-teal-500/50 focus:ring-1 focus:ring-teal-500/30 transition-all"
                />
              </div>

              <label className="flex items-start gap-3 cursor-pointer">
                <div className="relative mt-0.5">
                  <input
                    type="checkbox"
                    checked={consent}
                    onChange={(e) => setConsent(e.target.checked)}
                    className="sr-only"
                    required
                  />
                  <div className={`w-5 h-5 rounded border-2 transition-all flex items-center justify-center ${
                    consent ? "bg-teal-500 border-teal-500" : "border-white/30"
                  }`}>
                    {consent && (
                      <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                      </svg>
                    )}
                  </div>
                </div>
                <span className="text-white/60 text-sm">
                  I agree to receive the relocation plan and occasional travel tool updates.
                </span>
              </label>

              {error && (
                <div className="p-3 bg-red-500/10 border border-red-500/30 rounded-lg text-red-400 text-sm">
                  {error}
                </div>
              )}

              <button
                type="submit"
                disabled={!email || !consent || submitting}
                className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-600 text-white font-bold rounded-xl shadow-lg shadow-teal-500/30 hover:shadow-teal-500/50 transition-all disabled:opacity-50 disabled:cursor-not-allowed disabled:shadow-none"
              >
                {submitting ? "Submitting..." : "Get My Plan"}
              </button>

              <p className="text-white/30 text-xs text-center">
                We respect your privacy.{" "}
                <button
                  type="button"
                  onClick={() => window.open("/privacy", "_blank")}
                  className="text-teal-400/60 hover:text-teal-400 underline"
                >
                  Privacy Policy
                </button>
              </p>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}
